name: tea_scanner
description: Tea QR Scanner with Blockchain Integration
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  http: ^1.1.0
  web3dart: ^2.7.3
  shared_preferences: ^2.2.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  image_picker: ^1.0.4
  fluttertoast: ^8.2.4
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true